post_install() {

  # create systemd-boot entry
  if [ $(bootctl is-installed) = "yes" ]
  then
    kernel-install add "${1}-a3700" -
  fi

}

post_upgrade() {

  # update systemd-boot entry
  if [ $(bootctl is-installed) = "yes" ]
  then
    kernel-install remove "${2}-a3700"
    kernel-install add "${1}-a3700" -
  fi

}

post_remove() {

  # remove systemd-boot entry
  if [ $(bootctl is-installed) = "yes" ]
  then
    kernel-install remove "${1}-a3700"
  fi

}
